language: php
php:
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - composer test
  - CODECLIMATE_REPO_TOKEN=71e19b84b0cdb8a2ea357254546633169b0688a910566ec2c36fb8e803a79b5c ./vendor/bin/test-reporter
